---
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

test_python:
  stage: test
  image: python:3-alpine
  script:
    - python -V
    - pip install -q virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -q pytest
    - pytest ./python/*/*_test.py
