---
include:
  - template: Jobs/Code-Intelligence.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

test_python:
  stage: test
  image: python:3-alpine
  artifacts:
    reports:
      junit: pytest.xml
  script:
    - source .gitlab/ci.sh
    - ci_section_start setup
    - python -V
    - pip install -q virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -q pylint pytest
    - ci_section_end setup
    - ci_section_start pylint
    - pylint ./python/ || true
    - ci_section_end pylint
    - ci_section_start pytest
    - pytest --junitxml="pytest.xml" ./python/
    - ci_section_end pytest
