---
include:
  - template: Jobs/Code-Intelligence.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

elixir:
  stage: test
  image: elixir:alpine
  cache:
    key: elixir
    paths:
      - .cache/elixir/
      - elixir/*/_build/
      - elixir/*/deps/
  artifacts:
    reports:
      junit: ./.cache/elixir/build/test/lib/*/test-junit-report.xml
  script:
    - source .gitlab/ci.sh
    - for CMD in setup lint test ; do ci_section "elixir-${CMD}" "bin/elixir-${CMD}" ; done

python:
  stage: test
  image: python:3-alpine
  cache:
    key: python
    paths:
      - .cache/python
  artifacts:
    reports:
      cobertura: python-coverage.xml
      junit: pytest.xml
  before_script:
    - apk add --no-cache bash
  script:
    - source .gitlab/ci.sh
    - for CMD in setup lint test ; do ci_section "python-${CMD}" "bin/python-${CMD}" ; done
